name: snap_panel
description: "A highly customizable sliding panel component for Flutter, supporting multi-snap points, drag gestures, spring animations, and scroll linkage."
version: 0.0.4
homepage: https://github.com/ZxlHyy/snap_panel
repository: https://github.com/ZxlHyy/snap_panel
issue_tracker: https://github.com/ZxlHyy/snap_panel/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: